### ISSUE TITLE
Climacell.co no longer exists

### ISSUE THREAD

**Issue by CompKingCanada** [bpaauwe/udi-climacell-poly#10]
api.climacell.co is no longer a valid DNS entry.  Appears to have been rebranded, purchased by tomorrow.io on main website.

Been a while since I looked at my Polyglot

Options:
1) Same API / New DNS = Update this Polyglot
2) Different API = New Polyglot

Has this been looked at?  Perhaps this should be removed from NodeServer Store to avoid confusion

**Comment by CompKingCanada** [comment]
Looking at code this looks like V4 API  1.1.0 update should resolve.  Disregard.

**Comment by bpaauwe** [comment]
The node server was updated to support tomorrow.io quite a while ago.

The main key in the node server database is the node server name, thus, it's not really possible to change the name without essentially creating a new node server.
