### ISSUE TITLE
Node substitute variables

### ISSUE THREAD

**Issue by oper859** [bpaauwe/udi-climacell-poly#5]
I had all working fine, but had to re-install the server node and now I see that two Node Substitutes Variables for the Forecast Node are returning numbers instead of words. This is for GV19 that must return the day of the week and now returning one digit number and GV13 that must return the Weather conditions and now is returning a 2 digit number.  The corresponding fields in ISY are populated correctly with description, not numbers. I use the node substitutes variables in a small program that is sending me weather forecast everyday. 
This is the program:

Forecast for: ${sys.node.n001_forecast_1.GV19}
Weather Conditions: ${sys.node.n001_forecast_1.GV13}
Chance of Rain: ${sys.node.n001_forecast_1.GV18}
Rain Amount: ${sys.node.n001_forecast_1.GV6}
Max Temp: ${sys.node.n001_forecast_1.GV0}
Min Temp: ${sys.node.n001_forecast_1.GV1}
Max Wind: ${sys.node.n001_forecast_1.GV7}

And these are the results:

Forecast for: 1
Weather Conditions: 15
Chance of Rain: 10%
Rain Amount: 0.3 mm
Max Temp: 21.1°C
Min Temp: 11.7°C
Max Wind: 5.9 meters/sec

**Comment by bpaauwe** [comment]
I believe the ISY needs to be rebooted to re-read the mapping files.

All node values are numbers. There's a mapping file that will map numbers to text strings for specific values.  This mapping file is read by both the ISY and the Admin Console separately. 

I don't know what triggers the ISY to read or not read those files, but last time someone reported an issue like this, UDI's response was to reboot the ISY.

**Comment by oper859** [comment]
Indeed, a restart of ISY followed by a restart of the node server on Polyglot solved the issue. Thanks !
